In [ ]:
from google.colab import drive
import pandas as pd
import os
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
data = pd.read_csv('/content/drive/My Drive/adult_train.csv')
#Data can be accessed here: https://www.kaggle.com/datasets/sagnikpatra/uci-adult-census-data-dataset
data

,Age,Workclass,fnlwgt,Education,Education_Num,Martial_Status,Occupation,Relationship,Race,Sex,Capital_Gain,Capital_Loss,Hours_per_week,Country,Target
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
race_count = data['Race'].value_counts()

average_age_men = data[data['Sex'] == 'Male']['Age'].mean()

percentage_bachelors = (data['Education'] == 'Bachelors').mean() * 100

advanced_education = ['Bachelors', 'Masters', 'Doctorate']
higher_education = data['Education'].isin(advanced_education)
percentage_high_earning = (data[higher_education]['Target'] == '>50K').mean() * 100

no_higher_education = ~higher_education
percentage_no_high_earning = (data[no_higher_education]['Target'] == '>50K').mean() * 100

min_work_hours = data['Hours_per_week'].min()

num_min_workers = data[data['Hours_per_week'] == min_work_hours]
rich_percentage = (num_min_workers['Target'] == '>50K').mean() * 100

country_stats = data['Country'].value_counts()
country_earnings = data[data['Target'] == '>50K']['Country'].value_counts()
highest_earning_country = (country_earnings / country_stats).idxmax()
highest_earning_country_percentage = (country_earnings / country_stats).max() * 100

indian_occupation_stats = data[(data['Country'] == 'India') & (data['Target'] == '>50K')]['Occupation'].value_counts()

print("Task 1: Race count:\n", race_count)
print("\nTask 2: Average age of men:", average_age_men)
print("\nTask 3: Percentage with a Bachelor's degree:", percentage_bachelors)
print("\nTask 4: Percentage with advanced education earning >50K:", percentage_high_earning)
print("\nTask 5: Percentage without advanced education earning >50K:", percentage_no_high_earning)
print("\nTask 6: Minimum work hours per week:", min_work_hours)
print("\nTask 7: Percentage of minimum work hours with >50K:", rich_percentage)
print("\nTask 8: Country with the highest percentage earning >50K:", highest_earning_country)

Task 1: Race count:
  White                 27816
 Black                  3124
 Asian-Pac-Islander     1039
 Amer-Indian-Eskimo      311
 Other                   271
Name: Race, dtype: int64

Task 2: Average age of men: nan

Task 3: Percentage with a Bachelor's degree: 0.0

Task 4: Percentage with advanced education earning >50K: nan

Task 5: Percentage without advanced education earning >50K: 0.0

Task 6: Minimum work hours per week: 1

Task 7: Percentage of minimum work hours with >50K: 0.0

Task 8: Country with the highest percentage earning >50K: nan